// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbkkvvtxkywgitvzigto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZia2t2dnR4a3l3Z2l0dnppZ3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTkzODAsImV4cCI6MjA3MTk3NTM4MH0.14GAfFyR_X11hyyJfmccf6Q7SSxmAO6ULkOHyUUBvsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});